###########
# site.title

title:    '&#x2694 Overworlders	&#x2694'
subtitle: 'CS 175: Project in AI (in Minecraft)'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
